enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

[Twitter]
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko"
build-mode = "module"
version = "auto"
include-stock = "split"
included-patches = "'Bring back twitter'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"

[Twitter-NewX]
app-name = "Twitter"
patches-source = "crimera/piko-newx"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Piko NewX"
module-prop-name = "twitter-newx-jhc"
build-mode = "module"
version = "auto"
include-stock = "split"
included-patches = "'NewX: Restore Twitter branding'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
uptodown-dlurl = "https://twitter.en.uptodown.com/android"



